name: Quality
on:
  pull_request:
    branches:
      - main

jobs:
  InsightsReview:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHPInsights
        uses: docker://php:8-cli-alpine3.16
        with:
          entrypoint: .github/workflows/scripts/phpinsights.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_COMMIT_ID: ${{ github.event.pull_request.head.sha }}